// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Practica.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbVehiculosPorClientes = new HashSet<tbVehiculosPorClientes>();
        }

        public int Clie_Id { get; set; }
        public string Clie_DNI { get; set; }
        public string Clie_Nombre { get; set; }
        public string Clie_Apellido { get; set; }
        public string Clie_Sexo { get; set; }
        public int? Clie_Telefono { get; set; }
        public int? Esta_Id { get; set; }
        public string Muni_Id { get; set; }
        public int? Clie_Usua_Creacion { get; set; }
        public DateTime? Clie_Fecha_Creacion { get; set; }
        public int? Clie_Usua_Modifica { get; set; }
        public DateTime? Clie_Fecha_Modifica { get; set; }
        public bool? Clie_Estado { get; set; }

        [NotMapped]
        public string Dept_Id { get; set; }

        [NotMapped]
        public string Esta_Descripcion { get; set; }

        [NotMapped]
        public string Muni_Descripcion { get; set; }

        [NotMapped]
        public string Dept_Descripcion { get; set; }

        [NotMapped]
        public string Usua_Creacion { get; set; }

        [NotMapped]
        public string Usua_Modifica { get; set; }

        public virtual tbUsuarios Clie_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Clie_Usua_ModificaNavigation { get; set; }
        public virtual tbEstadosCiviles Esta { get; set; }
        public virtual tbMunicipios Muni { get; set; }
        public virtual ICollection<tbVehiculosPorClientes> tbVehiculosPorClientes { get; set; }
    }
}