// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Practica.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbClientes = new HashSet<tbClientes>();
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int Esta_Id { get; set; }
        public string Esta_Descripcion { get; set; }
        public int? Esta_Usua_Creacion { get; set; }
        public DateTime? Esta_Fecha_Creacion { get; set; }
        public int? Esta_Usua_Modifica { get; set; }
        public DateTime? Esta_Fecha_Modifica { get; set; }
        public bool? Esta_Estado { get; set; }

        [NotMapped]
        public string Usua_Creacion { get; set; }

        [NotMapped]
        public string Usua_Modifica { get; set; }
        public virtual tbUsuarios Esta_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Esta_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientes { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}