// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Practica.Entities.Entities
{
    public partial class tbMarcas
    {
        public tbMarcas()
        {
            tbModelos = new HashSet<tbModelos>();
        }

        public int Marc_Id { get; set; }
        public string Marc_Descripcion { get; set; }
        public int? Marc_Usua_Creacion { get; set; }
        public DateTime? Marc_Fecha_Creacion { get; set; }
        public int? Marc_Usuario_Modificiacion { get; set; }
        public DateTime? Marc_Fecha_Modificacion { get; set; }
        public bool? Marc_Estado { get; set; }

        [NotMapped]
        public string Usua_Creacion { get; set; }

        [NotMapped]
        public string Usua_Modifica { get; set; }

        public virtual tbUsuarios Marc_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Marc_Usuario_ModificiacionNavigation { get; set; }
        public virtual ICollection<tbModelos> tbModelos { get; set; }
    }
}