// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Practica.Entities.Entities
{
    public partial class tbModelos
    {
        public tbModelos()
        {
            tbVehiculos = new HashSet<tbVehiculos>();
        }

        public int Mode_Id { get; set; }
        public string Mode_Descripcion { get; set; }
        public int? Marc_Id { get; set; }
        public int? Mode_Usua_Creacion { get; set; }
        public DateTime? Mode_Fecha_Creacion { get; set; }
        public int? Mode_Usua_Modifica { get; set; }
        public DateTime? Mode_Fecha_Modifica { get; set; }
        public bool? Mode_Estado { get; set; }

        [NotMapped]
        public string Marc_Descripcion { get; set; }

        [NotMapped]
        public string Usua_Creacion { get; set; }

        [NotMapped]
        public string Usua_Modifica { get; set; }
        public virtual tbMarcas Marc { get; set; }
        public virtual tbUsuarios Mode_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Mode_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbVehiculos> tbVehiculos { get; set; }
    }
}