// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Practica.Entities.Entities
{
    public partial class tbSucursales
    {
        public tbSucursales()
        {
            tbPlanesPagosClientes = new HashSet<tbPlanesPagosClientes>();
        }

        public int Sucu_Id { get; set; }
        public string Sucu_Calle { get; set; }
        public string Sucu_Direccion { get; set; }
        public string Muni_Id { get; set; }
        public int? Sucu_Usua_Creacion { get; set; }
        public DateTime? Sucu_Fecha_Creacion { get; set; }
        public int? Sucu_Usua_Modi { get; set; }
        public DateTime? Sucu_Fecha_Modi { get; set; }
        public bool? Sucu_Estado { get; set; }

        [NotMapped]
        public string Muni_Descripcion { get; set; }

        [NotMapped]
        public string Dept_Descripcion { get; set; }

        [NotMapped]
        public string Dept_Id { get; set; }

        [NotMapped]
        public string Usua_Creacion { get; set; }

        [NotMapped]
        public string Usua_Modifica { get; set; }

        public virtual tbMunicipios Muni { get; set; }
        public virtual tbUsuarios Sucu_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Sucu_Usua_ModiNavigation { get; set; }
        public virtual ICollection<tbPlanesPagosClientes> tbPlanesPagosClientes { get; set; }
    }
}