// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Practica.Entities.Entities
{
    public partial class tbTipoCuotas
    {
        public tbTipoCuotas()
        {
            tbPlanesPagos = new HashSet<tbPlanesPagos>();
        }

        public int Ticu_Id { get; set; }
        public string Ticu_Descripcion { get; set; }
        public int? Ticu_Usua_Creacion { get; set; }
        public DateTime? Ticu_Fecha_Creacion { get; set; }
        public int? Ticu_Usua_Modi { get; set; }
        public DateTime? Ticu_Fecha_Modi { get; set; }
        public bool? Ticu_Estado { get; set; }

        [NotMapped]
        public string Usua_Creacion { get; set; }

        [NotMapped]
        public string Usua_Modifica { get; set; }

        public virtual tbUsuarios Ticu_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Ticu_Usua_ModiNavigation { get; set; }
        public virtual ICollection<tbPlanesPagos> tbPlanesPagos { get; set; }
    }
}