// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Practica.Entities.Entities
{
    public partial class tbVehiculos
    {
        public tbVehiculos()
        {
            tbVehiculosPorClientes = new HashSet<tbVehiculosPorClientes>();
        }

        [NotMapped]
        public string Vecl_Id { get; set; }
        public int Vehi_Id { get; set; }
        public string Vehi_Placa { get; set; }
        public string Vehi_Descripcion { get; set; }
        public string Vehi_Color { get; set; }
        public int? Vehi_Anio { get; set; }
        public int? Mode_Id { get; set; }
        public int? Vehi_Usua_Creacion { get; set; }
        public DateTime? Vehi_Fecha_Creacion { get; set; }
        public int? Vehi_Usua_Modifica { get; set; }
        public DateTime? Vehi_Fecha_Modifica { get; set; }
        public bool? Vehi_Estado { get; set; }

        [NotMapped]
        public string Mode_Descripcion { get; set; }

        [NotMapped]
        public string Marc_Descripcion { get; set; }

        [NotMapped]
        public string Cliente { get; set; }

        [NotMapped]
        public string Usua_Creacion { get; set; }

        [NotMapped]
        public string Usua_Modifica { get; set; }

        public virtual tbModelos Mode { get; set; }
        public virtual tbUsuarios Vehi_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Vehi_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbVehiculosPorClientes> tbVehiculosPorClientes { get; set; }
    }
}