// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Practica.Entities.Entities
{
    public partial class tbVehiculosPorClientes
    {
        public tbVehiculosPorClientes()
        {
            tbImagenesPorClientes = new HashSet<tbImagenesPorClientes>();
            tbPlanesPagos = new HashSet<tbPlanesPagos>();
        }

        public int Vecl_Id { get; set; }
        public int? Vehi_Id { get; set; }
        public int? Clie_Id { get; set; }
        public int? Vecl_Usua_Creacion { get; set; }
        public DateTime? Vecl_Fecha_Creacion { get; set; }
        public int? Vecl_Usua_Modifica { get; set; }
        public DateTime? Vecl_Fecha_Modifica { get; set; }
        public bool? Vecl_Estado { get; set; }

        [NotMapped]
        public string Usua_Creacion { get; set; }

        [NotMapped]
        public string Usua_Modifica { get; set; }

        public virtual tbClientes Clie { get; set; }
        public virtual tbUsuarios Vecl_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Vecl_Usua_ModificaNavigation { get; set; }
        public virtual tbVehiculos Vehi { get; set; }
        public virtual ICollection<tbImagenesPorClientes> tbImagenesPorClientes { get; set; }
        public virtual ICollection<tbPlanesPagos> tbPlanesPagos { get; set; }
    }
}